# action.yml
name: 'git-filter-repo-push'
description: 'Runs git-filter-repo and pushes the result to a target using ssh'
inputs:
    privateKey:
        description: 'Private SSH Key for pushing to the target repo'
        required: true
    targetOrg:
        description: 'The github organization (or user) of the target repository'
        required: true
    targetRepo:
        description: 'The target repository'
        required: true
    targetBranch:
        description: 'The target branch'
        required: true
    filterArguments:
        description: 'The raw arguments to pass to git-filter-repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SSH_PRIVATE_KEY: ${{ input.privateKey }}
    TARGET_ORG: ${{ input.targetOrg }}
    TARGET_REPO: ${{ input.targetRepo }}
    TARGET_BRANCH: ${{ input.targetBranch }}
  args:
    - ${{ input.filterArguments }}